baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'ssi'

[params]
title="Think & Do Tank Sciences, Société, Industrie"
slogan="Quatre structures se mobilisent pour mettre en place un dispositif de recherche, de prototypage d’outils de médiation industrielle et d’accompagnement à la transformation"
